name: kbkonlinetopup
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2025.2.25
  - libffi=3.4.4
  - ncurses=6.4
  - openssl=3.0.16
  - pip=25.1
  - python=3.10.16
  - readline=8.2
  - setuptools=78.1.1
  - sqlite=3.45.3
  - tk=8.6.14
  - wheel=0.45.1
  - xz=5.6.4
  - zlib=1.2.13
  - pip:
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.11.18
      - aiosignal==1.3.2
      - aiosqlite==0.21.0
      - altair==5.5.0
      - async-timeout==5.0.1
      - attrs==25.3.0
      - blinker==1.9.0
      - cachetools==5.5.2
      - certifi==2025.4.26
      - charset-normalizer==3.4.2
      - click==8.2.0
      - et-xmlfile==2.0.0
      - flask==3.1.1
      - flask-cors==5.0.1
      - frozenlist==1.6.0
      - gitdb==4.0.12
      - gitpython==3.1.44
      - idna==3.10
      - itsdangerous==2.2.0
      - jinja2==3.1.6
      - jsonschema==4.23.0
      - jsonschema-specifications==2025.4.1
      - markupsafe==3.0.2
      - multidict==6.4.3
      - narwhals==1.39.1
      - numpy==2.2.5
      - openpyxl==3.1.5
      - packaging==24.2
      - pandas==2.2.3
      - pillow==11.2.1
      - plotly==6.1.0
      - prometheus-client==0.21.1
      - propcache==0.3.1
      - protobuf==6.31.0
      - pyarrow==20.0.0
      - pydeck==0.9.1
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - referencing==0.36.2
      - requests==2.32.3
      - rpds-py==0.25.0
      - schedule==1.2.2
      - six==1.17.0
      - smmap==5.0.2
      - streamlit==1.45.1
      - tenacity==9.1.2
      - toml==0.10.2
      - tornado==6.5
      - typing-extensions==4.13.2
      - tzdata==2025.2
      - urllib3==2.4.0
      - watchdog==6.0.0
      - werkzeug==3.1.3
      - yarl==1.20.0
